language: go
sudo: false
dist: trusty
go:
  - 1.7
  - 1.8
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - $HOME/gopath/bin/goveralls -repotoken 8lMA45pznwDRJhGWY0ysJkanbzE8FLVD9
  - go test -race -v .